services:
  streamlit:
    build: .
    container_name: streamlit-app
    expose:
      - "8501"
    restart: always

  nginx-proxy:
    image: nginx:1.18.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
    depends_on:
      - streamlit
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --dry-run
      --email your_email@example.com
      -d goathub.shop -d www.goathub.shop
      --agree-tos --no-eff-email"
